//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace SOSI.Produktspesifikasjon.Reguleringsplanforslag.Planbestemmelser
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ReguleringsplanbestemmelserListe", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReguleringsplanbestemmelserListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ReguleringsplanbestemmelserType> _reguleringsplanbestemmelser;
        
        [System.Xml.Serialization.XmlElementAttribute("reguleringsplanbestemmelser")]
        public System.Collections.ObjectModel.Collection<ReguleringsplanbestemmelserType> Reguleringsplanbestemmelser
        {
            get
            {
                return this._reguleringsplanbestemmelser;
            }
            private set
            {
                this._reguleringsplanbestemmelser = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReguleringsplanbestemmelserSpecified
        {
            get
            {
                return (this.Reguleringsplanbestemmelser.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public ReguleringsplanbestemmelserListe()
        {
            this._reguleringsplanbestemmelser = new System.Collections.ObjectModel.Collection<ReguleringsplanbestemmelserType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ReguleringsplanbestemmelserType", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Reguleringsplanbestemmelser", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    public partial class ReguleringsplanbestemmelserType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("nasjonalArealplanId", IsNullable=true)]
        public NasjonalArealplanIdType NasjonalArealplanId { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("plantype", IsNullable=true)]
        public KodeType Plantype { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("plannavn", IsNullable=true)]
        public string Plannavn { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lovreferanse", IsNullable=true)]
        public KodeType Lovreferanse { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("versjonsdato", IsNullable=true, DataType="date")]
        public System.Nullable<System.DateTime> VersjonsdatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool VersjonsdatoValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> Versjonsdato
        {
            get
            {
                if (this.VersjonsdatoValueSpecified)
                {
                    return this.VersjonsdatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.VersjonsdatoValue = value.GetValueOrDefault();
                this.VersjonsdatoValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("versjonsnummer", IsNullable=true)]
        public string Versjonsnummer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("alternativReferanse", IsNullable=true)]
        public string AlternativReferanse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("planhensikt", IsNullable=true)]
        public PlanensHensiktType Planhensikt { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<FellesbestemmelseType> _fellesbestemmelse;
        
        [System.Xml.Serialization.XmlArrayAttribute("fellesbestemmelse", IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("fellesbestemmelse", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
            "anbestemmelser")]
        public System.Collections.ObjectModel.Collection<FellesbestemmelseType> Fellesbestemmelse
        {
            get
            {
                return this._fellesbestemmelse;
            }
            private set
            {
                this._fellesbestemmelse = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FellesbestemmelseSpecified
        {
            get
            {
                return (this.Fellesbestemmelse.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public ReguleringsplanbestemmelserType()
        {
            this._fellesbestemmelse = new System.Collections.ObjectModel.Collection<FellesbestemmelseType>();
            this._kravOmDetaljregulering = new System.Collections.ObjectModel.Collection<KravOmDetaljreguleringType>();
            this._formaalsbestemmelse = new System.Collections.ObjectModel.Collection<BestemmelseArealformaalType>();
            this._hensynsbestemmelse = new System.Collections.ObjectModel.Collection<BestemmelseHensynssoneType>();
            this._omraadebestemmelse = new System.Collections.ObjectModel.Collection<BestemmelseOmraadeType>();
            this._rekkefoelgebestemmelse = new System.Collections.ObjectModel.Collection<BestemmelseRekkefoelgeType>();
            this._juridiskDokument = new System.Collections.ObjectModel.Collection<JuridiskBindendeDokumentType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<KravOmDetaljreguleringType> _kravOmDetaljregulering;
        
        [System.Xml.Serialization.XmlArrayAttribute("kravOmDetaljregulering", IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("kravomdetaljregulering", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
            "anbestemmelser")]
        public System.Collections.ObjectModel.Collection<KravOmDetaljreguleringType> KravOmDetaljregulering
        {
            get
            {
                return this._kravOmDetaljregulering;
            }
            private set
            {
                this._kravOmDetaljregulering = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KravOmDetaljreguleringSpecified
        {
            get
            {
                return (this.KravOmDetaljregulering.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BestemmelseArealformaalType> _formaalsbestemmelse;
        
        [System.Xml.Serialization.XmlArrayAttribute("formaalsbestemmelse", IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("bestemmelsearealformaal", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
            "anbestemmelser")]
        public System.Collections.ObjectModel.Collection<BestemmelseArealformaalType> Formaalsbestemmelse
        {
            get
            {
                return this._formaalsbestemmelse;
            }
            private set
            {
                this._formaalsbestemmelse = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FormaalsbestemmelseSpecified
        {
            get
            {
                return (this.Formaalsbestemmelse.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BestemmelseHensynssoneType> _hensynsbestemmelse;
        
        [System.Xml.Serialization.XmlArrayAttribute("hensynsbestemmelse", IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("bestemmelsehensynssone", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
            "anbestemmelser")]
        public System.Collections.ObjectModel.Collection<BestemmelseHensynssoneType> Hensynsbestemmelse
        {
            get
            {
                return this._hensynsbestemmelse;
            }
            private set
            {
                this._hensynsbestemmelse = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HensynsbestemmelseSpecified
        {
            get
            {
                return (this.Hensynsbestemmelse.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BestemmelseOmraadeType> _omraadebestemmelse;
        
        [System.Xml.Serialization.XmlArrayAttribute("omraadebestemmelse", IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("bestemmelseomraade", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
            "anbestemmelser")]
        public System.Collections.ObjectModel.Collection<BestemmelseOmraadeType> Omraadebestemmelse
        {
            get
            {
                return this._omraadebestemmelse;
            }
            private set
            {
                this._omraadebestemmelse = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OmraadebestemmelseSpecified
        {
            get
            {
                return (this.Omraadebestemmelse.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BestemmelseRekkefoelgeType> _rekkefoelgebestemmelse;
        
        [System.Xml.Serialization.XmlArrayAttribute("rekkefoelgebestemmelse", IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("bestemmelserekkefoelge", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
            "anbestemmelser")]
        public System.Collections.ObjectModel.Collection<BestemmelseRekkefoelgeType> Rekkefoelgebestemmelse
        {
            get
            {
                return this._rekkefoelgebestemmelse;
            }
            private set
            {
                this._rekkefoelgebestemmelse = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RekkefoelgebestemmelseSpecified
        {
            get
            {
                return (this.Rekkefoelgebestemmelse.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<JuridiskBindendeDokumentType> _juridiskDokument;
        
        [System.Xml.Serialization.XmlArrayAttribute("juridiskDokument", IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("juridiskbindendedokument", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
            "anbestemmelser")]
        public System.Collections.ObjectModel.Collection<JuridiskBindendeDokumentType> JuridiskDokument
        {
            get
            {
                return this._juridiskDokument;
            }
            private set
            {
                this._juridiskDokument = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JuridiskDokumentSpecified
        {
            get
            {
                return (this.JuridiskDokument.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _dataFormatProvider = "SERES";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("dataFormatProvider")]
        public string DataFormatProvider
        {
            get
            {
                return this._dataFormatProvider;
            }
            set
            {
                this._dataFormatProvider = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _dataFormatId = "6825";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("dataFormatId")]
        public string DataFormatId
        {
            get
            {
                return this._dataFormatId;
            }
            set
            {
                this._dataFormatId = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _dataFormatVersion = "45983";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("dataFormatVersion")]
        public string DataFormatVersion
        {
            get
            {
                return this._dataFormatVersion;
            }
            set
            {
                this._dataFormatVersion = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NasjonalArealplanIdType", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("NasjonalArealplanId", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    public partial class NasjonalArealplanIdType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("administrativEnhet", IsNullable=true)]
        public AdministrativEnhetskodeType AdministrativEnhet { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("planidentifikasjon", IsNullable=true)]
        public string Planidentifikasjon { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AdministrativEnhetskodeType", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("AdministrativEnhetskode", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    public partial class AdministrativEnhetskodeType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("kommunenummer", IsNullable=true)]
        public string Kommunenummer { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("KodeType", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Kode", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    public partial class KodeType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("kodeverdi")]
        public string Kodeverdi { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("kodebeskrivelse", IsNullable=true)]
        public string Kodebeskrivelse { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PlanensHensiktType", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("PlanensHensikt", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    public partial class PlanensHensiktType : AbstraktPlanbestemmelseType
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AbstraktPlanbestemmelseType", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("AbstraktPlanbestemmelse", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BestemmelseArealformaalType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BestemmelseHensynssoneType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BestemmelseOmraadeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BestemmelseRekkefoelgeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FellesbestemmelseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlanensHensiktType))]
    public abstract partial class AbstraktPlanbestemmelseType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("nummerering")]
        public string Nummerering { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("overskrift", IsNullable=true)]
        public string Overskrift { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("tekst", IsNullable=true)]
        public FormatertTekstType Tekst { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("sorteringsrekkefoelge")]
        public string Sorteringsrekkefoelge { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("versjonsdato", IsNullable=true, DataType="date")]
        public System.Nullable<System.DateTime> VersjonsdatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool VersjonsdatoValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> Versjonsdato
        {
            get
            {
                if (this.VersjonsdatoValueSpecified)
                {
                    return this.VersjonsdatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.VersjonsdatoValue = value.GetValueOrDefault();
                this.VersjonsdatoValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("versjonsnummer", IsNullable=true)]
        public string Versjonsnummer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("alternativReferanse", IsNullable=true)]
        public string AlternativReferanse { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FormatertTekstType", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("FormatertTekst", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    public partial class FormatertTekstType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("tekstInnhold", IsNullable=true)]
        public string TekstInnhold { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("tekstFormat", IsNullable=true)]
        public KodeType TekstFormat { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FellesbestemmelseListe", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FellesbestemmelseListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<FellesbestemmelseType> _fellesbestemmelse;
        
        [System.Xml.Serialization.XmlElementAttribute("fellesbestemmelse")]
        public System.Collections.ObjectModel.Collection<FellesbestemmelseType> Fellesbestemmelse
        {
            get
            {
                return this._fellesbestemmelse;
            }
            private set
            {
                this._fellesbestemmelse = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FellesbestemmelseSpecified
        {
            get
            {
                return (this.Fellesbestemmelse.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public FellesbestemmelseListe()
        {
            this._fellesbestemmelse = new System.Collections.ObjectModel.Collection<FellesbestemmelseType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FellesbestemmelseType", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Fellesbestemmelse", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    public partial class FellesbestemmelseType : AbstraktPlanbestemmelseType
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("KravOmDetaljreguleringListe", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KravOmDetaljreguleringListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<KravOmDetaljreguleringType> _kravomdetaljregulering;
        
        [System.Xml.Serialization.XmlElementAttribute("kravomdetaljregulering")]
        public System.Collections.ObjectModel.Collection<KravOmDetaljreguleringType> Kravomdetaljregulering
        {
            get
            {
                return this._kravomdetaljregulering;
            }
            private set
            {
                this._kravomdetaljregulering = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KravomdetaljreguleringSpecified
        {
            get
            {
                return (this.Kravomdetaljregulering.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public KravOmDetaljreguleringListe()
        {
            this._kravomdetaljregulering = new System.Collections.ObjectModel.Collection<KravOmDetaljreguleringType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("KravOmDetaljreguleringType", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("KravOmDetaljregulering", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    public partial class KravOmDetaljreguleringType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _feltnavn;
        
        [System.Xml.Serialization.XmlElementAttribute("feltnavn", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<string> Feltnavn
        {
            get
            {
                return this._feltnavn;
            }
            private set
            {
                this._feltnavn = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FeltnavnSpecified
        {
            get
            {
                return (this.Feltnavn.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public KravOmDetaljreguleringType()
        {
            this._feltnavn = new System.Collections.ObjectModel.Collection<string>();
            this._bestemmelseOmraadenavn = new System.Collections.ObjectModel.Collection<string>();
            this._hensynSonenavn = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("KravTilDetaljreguleringen", IsNullable=true)]
        public FormatertTekstType KravTilDetaljreguleringen { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _bestemmelseOmraadenavn;
        
        [System.Xml.Serialization.XmlElementAttribute("bestemmelseOmraadenavn", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<string> BestemmelseOmraadenavn
        {
            get
            {
                return this._bestemmelseOmraadenavn;
            }
            private set
            {
                this._bestemmelseOmraadenavn = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BestemmelseOmraadenavnSpecified
        {
            get
            {
                return (this.BestemmelseOmraadenavn.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _hensynSonenavn;
        
        [System.Xml.Serialization.XmlElementAttribute("hensynSonenavn", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<string> HensynSonenavn
        {
            get
            {
                return this._hensynSonenavn;
            }
            private set
            {
                this._hensynSonenavn = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HensynSonenavnSpecified
        {
            get
            {
                return (this.HensynSonenavn.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BestemmelseArealformaalListe", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BestemmelseArealformaalListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BestemmelseArealformaalType> _bestemmelsearealformaal;
        
        [System.Xml.Serialization.XmlElementAttribute("bestemmelsearealformaal")]
        public System.Collections.ObjectModel.Collection<BestemmelseArealformaalType> Bestemmelsearealformaal
        {
            get
            {
                return this._bestemmelsearealformaal;
            }
            private set
            {
                this._bestemmelsearealformaal = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BestemmelsearealformaalSpecified
        {
            get
            {
                return (this.Bestemmelsearealformaal.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public BestemmelseArealformaalListe()
        {
            this._bestemmelsearealformaal = new System.Collections.ObjectModel.Collection<BestemmelseArealformaalType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BestemmelseArealformaalType", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("BestemmelseArealformaal", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    public partial class BestemmelseArealformaalType : AbstraktPlanbestemmelseType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("gjelderHovedformaal", IsNullable=true)]
        public KodeType GjelderHovedformaal { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("fellesForHovedformaal", IsNullable=true)]
        public System.Nullable<bool> FellesForHovedformaalValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool FellesForHovedformaalValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> FellesForHovedformaal
        {
            get
            {
                if (this.FellesForHovedformaalValueSpecified)
                {
                    return this.FellesForHovedformaalValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.FellesForHovedformaalValue = value.GetValueOrDefault();
                this.FellesForHovedformaalValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _feltnavn;
        
        [System.Xml.Serialization.XmlElementAttribute("feltnavn", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<string> Feltnavn
        {
            get
            {
                return this._feltnavn;
            }
            private set
            {
                this._feltnavn = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FeltnavnSpecified
        {
            get
            {
                return (this.Feltnavn.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public BestemmelseArealformaalType()
        {
            this._feltnavn = new System.Collections.ObjectModel.Collection<string>();
            this._bestemmelseOmraadenavn = new System.Collections.ObjectModel.Collection<string>();
            this._objektnavn = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _bestemmelseOmraadenavn;
        
        [System.Xml.Serialization.XmlElementAttribute("bestemmelseOmraadenavn", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<string> BestemmelseOmraadenavn
        {
            get
            {
                return this._bestemmelseOmraadenavn;
            }
            private set
            {
                this._bestemmelseOmraadenavn = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BestemmelseOmraadenavnSpecified
        {
            get
            {
                return (this.BestemmelseOmraadenavn.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _objektnavn;
        
        [System.Xml.Serialization.XmlElementAttribute("objektnavn", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<string> Objektnavn
        {
            get
            {
                return this._objektnavn;
            }
            private set
            {
                this._objektnavn = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ObjektnavnSpecified
        {
            get
            {
                return (this.Objektnavn.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BestemmelseHensynssoneListe", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BestemmelseHensynssoneListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BestemmelseHensynssoneType> _bestemmelsehensynssone;
        
        [System.Xml.Serialization.XmlElementAttribute("bestemmelsehensynssone")]
        public System.Collections.ObjectModel.Collection<BestemmelseHensynssoneType> Bestemmelsehensynssone
        {
            get
            {
                return this._bestemmelsehensynssone;
            }
            private set
            {
                this._bestemmelsehensynssone = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BestemmelsehensynssoneSpecified
        {
            get
            {
                return (this.Bestemmelsehensynssone.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public BestemmelseHensynssoneListe()
        {
            this._bestemmelsehensynssone = new System.Collections.ObjectModel.Collection<BestemmelseHensynssoneType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BestemmelseHensynssoneType", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("BestemmelseHensynssone", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    public partial class BestemmelseHensynssoneType : AbstraktPlanbestemmelseType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("hensynskategori", IsNullable=true)]
        public KodeType Hensynskategori { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _hensynSonenavn;
        
        [System.Xml.Serialization.XmlElementAttribute("hensynSonenavn", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<string> HensynSonenavn
        {
            get
            {
                return this._hensynSonenavn;
            }
            private set
            {
                this._hensynSonenavn = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HensynSonenavnSpecified
        {
            get
            {
                return (this.HensynSonenavn.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public BestemmelseHensynssoneType()
        {
            this._hensynSonenavn = new System.Collections.ObjectModel.Collection<string>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BestemmelseOmraadeListe", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BestemmelseOmraadeListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BestemmelseOmraadeType> _bestemmelseomraade;
        
        [System.Xml.Serialization.XmlElementAttribute("bestemmelseomraade")]
        public System.Collections.ObjectModel.Collection<BestemmelseOmraadeType> Bestemmelseomraade
        {
            get
            {
                return this._bestemmelseomraade;
            }
            private set
            {
                this._bestemmelseomraade = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BestemmelseomraadeSpecified
        {
            get
            {
                return (this.Bestemmelseomraade.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public BestemmelseOmraadeListe()
        {
            this._bestemmelseomraade = new System.Collections.ObjectModel.Collection<BestemmelseOmraadeType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BestemmelseOmraadeType", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("BestemmelseOmraade", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    public partial class BestemmelseOmraadeType : AbstraktPlanbestemmelseType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _bestemmelseOmraadenavn;
        
        [System.Xml.Serialization.XmlElementAttribute("bestemmelseOmraadenavn", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<string> BestemmelseOmraadenavn
        {
            get
            {
                return this._bestemmelseOmraadenavn;
            }
            private set
            {
                this._bestemmelseOmraadenavn = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BestemmelseOmraadenavnSpecified
        {
            get
            {
                return (this.BestemmelseOmraadenavn.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public BestemmelseOmraadeType()
        {
            this._bestemmelseOmraadenavn = new System.Collections.ObjectModel.Collection<string>();
            this._feltnavn = new System.Collections.ObjectModel.Collection<string>();
            this._objektnavn = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _feltnavn;
        
        [System.Xml.Serialization.XmlElementAttribute("feltnavn", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<string> Feltnavn
        {
            get
            {
                return this._feltnavn;
            }
            private set
            {
                this._feltnavn = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FeltnavnSpecified
        {
            get
            {
                return (this.Feltnavn.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _objektnavn;
        
        [System.Xml.Serialization.XmlElementAttribute("objektnavn", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<string> Objektnavn
        {
            get
            {
                return this._objektnavn;
            }
            private set
            {
                this._objektnavn = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ObjektnavnSpecified
        {
            get
            {
                return (this.Objektnavn.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BestemmelseRekkefoelgeListe", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BestemmelseRekkefoelgeListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BestemmelseRekkefoelgeType> _bestemmelserekkefoelge;
        
        [System.Xml.Serialization.XmlElementAttribute("bestemmelserekkefoelge")]
        public System.Collections.ObjectModel.Collection<BestemmelseRekkefoelgeType> Bestemmelserekkefoelge
        {
            get
            {
                return this._bestemmelserekkefoelge;
            }
            private set
            {
                this._bestemmelserekkefoelge = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BestemmelserekkefoelgeSpecified
        {
            get
            {
                return (this.Bestemmelserekkefoelge.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public BestemmelseRekkefoelgeListe()
        {
            this._bestemmelserekkefoelge = new System.Collections.ObjectModel.Collection<BestemmelseRekkefoelgeType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BestemmelseRekkefoelgeType", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("BestemmelseRekkefoelge", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    public partial class BestemmelseRekkefoelgeType : AbstraktPlanbestemmelseType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _bestemmelseOmraadenavn;
        
        [System.Xml.Serialization.XmlElementAttribute("bestemmelseOmraadenavn", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<string> BestemmelseOmraadenavn
        {
            get
            {
                return this._bestemmelseOmraadenavn;
            }
            private set
            {
                this._bestemmelseOmraadenavn = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BestemmelseOmraadenavnSpecified
        {
            get
            {
                return (this.BestemmelseOmraadenavn.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public BestemmelseRekkefoelgeType()
        {
            this._bestemmelseOmraadenavn = new System.Collections.ObjectModel.Collection<string>();
            this._feltnavn = new System.Collections.ObjectModel.Collection<string>();
            this._hensynSonenavn = new System.Collections.ObjectModel.Collection<string>();
            this._objektnavn = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _feltnavn;
        
        [System.Xml.Serialization.XmlElementAttribute("feltnavn", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<string> Feltnavn
        {
            get
            {
                return this._feltnavn;
            }
            private set
            {
                this._feltnavn = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FeltnavnSpecified
        {
            get
            {
                return (this.Feltnavn.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _hensynSonenavn;
        
        [System.Xml.Serialization.XmlElementAttribute("hensynSonenavn", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<string> HensynSonenavn
        {
            get
            {
                return this._hensynSonenavn;
            }
            private set
            {
                this._hensynSonenavn = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HensynSonenavnSpecified
        {
            get
            {
                return (this.HensynSonenavn.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("rekkefoelgeangivelse", IsNullable=true)]
        public KodeType Rekkefoelgeangivelse { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _objektnavn;
        
        [System.Xml.Serialization.XmlElementAttribute("objektnavn", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<string> Objektnavn
        {
            get
            {
                return this._objektnavn;
            }
            private set
            {
                this._objektnavn = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ObjektnavnSpecified
        {
            get
            {
                return (this.Objektnavn.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JuridiskBindendeDokumentListe", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JuridiskBindendeDokumentListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<JuridiskBindendeDokumentType> _juridiskbindendedokument;
        
        [System.Xml.Serialization.XmlElementAttribute("juridiskbindendedokument")]
        public System.Collections.ObjectModel.Collection<JuridiskBindendeDokumentType> Juridiskbindendedokument
        {
            get
            {
                return this._juridiskbindendedokument;
            }
            private set
            {
                this._juridiskbindendedokument = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JuridiskbindendedokumentSpecified
        {
            get
            {
                return (this.Juridiskbindendedokument.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public JuridiskBindendeDokumentListe()
        {
            this._juridiskbindendedokument = new System.Collections.ObjectModel.Collection<JuridiskBindendeDokumentType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JuridiskBindendeDokumentType", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("JuridiskBindendeDokument", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    public partial class JuridiskBindendeDokumentType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("tittel")]
        public string Tittel { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("dokumentreferanse")]
        public string Dokumentreferanse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("sammendrag", IsNullable=true)]
        public string Sammendrag { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("rapportnummer", IsNullable=true)]
        public string Rapportnummer { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("dokumentetsDato", IsNullable=true, DataType="dateTime")]
        public System.Nullable<System.DateTime> DokumentetsDatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool DokumentetsDatoValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> DokumentetsDato
        {
            get
            {
                if (this.DokumentetsDatoValueSpecified)
                {
                    return this.DokumentetsDatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.DokumentetsDatoValue = value.GetValueOrDefault();
                this.DokumentetsDatoValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("KodeListe", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KodeListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<KodeType> _kode;
        
        [System.Xml.Serialization.XmlElementAttribute("kode")]
        public System.Collections.ObjectModel.Collection<KodeType> Kode
        {
            get
            {
                return this._kode;
            }
            private set
            {
                this._kode = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KodeSpecified
        {
            get
            {
                return (this.Kode.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public KodeListe()
        {
            this._kode = new System.Collections.ObjectModel.Collection<KodeType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AbstraktPlanbestemmelseListe", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AbstraktPlanbestemmelseListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AbstraktPlanbestemmelseType> _abstraktplanbestemmelse;
        
        [System.Xml.Serialization.XmlElementAttribute("abstraktplanbestemmelse")]
        public System.Collections.ObjectModel.Collection<AbstraktPlanbestemmelseType> Abstraktplanbestemmelse
        {
            get
            {
                return this._abstraktplanbestemmelse;
            }
            private set
            {
                this._abstraktplanbestemmelse = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AbstraktplanbestemmelseSpecified
        {
            get
            {
                return (this.Abstraktplanbestemmelse.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public AbstraktPlanbestemmelseListe()
        {
            this._abstraktplanbestemmelse = new System.Collections.ObjectModel.Collection<AbstraktPlanbestemmelseType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NasjonalArealplanIdListe", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NasjonalArealplanIdListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<NasjonalArealplanIdType> _nasjonalarealplanid;
        
        [System.Xml.Serialization.XmlElementAttribute("nasjonalarealplanid")]
        public System.Collections.ObjectModel.Collection<NasjonalArealplanIdType> Nasjonalarealplanid
        {
            get
            {
                return this._nasjonalarealplanid;
            }
            private set
            {
                this._nasjonalarealplanid = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NasjonalarealplanidSpecified
        {
            get
            {
                return (this.Nasjonalarealplanid.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public NasjonalArealplanIdListe()
        {
            this._nasjonalarealplanid = new System.Collections.ObjectModel.Collection<NasjonalArealplanIdType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PlanensHensiktListe", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlanensHensiktListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PlanensHensiktType> _planenshensikt;
        
        [System.Xml.Serialization.XmlElementAttribute("planenshensikt")]
        public System.Collections.ObjectModel.Collection<PlanensHensiktType> Planenshensikt
        {
            get
            {
                return this._planenshensikt;
            }
            private set
            {
                this._planenshensikt = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlanenshensiktSpecified
        {
            get
            {
                return (this.Planenshensikt.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public PlanensHensiktListe()
        {
            this._planenshensikt = new System.Collections.ObjectModel.Collection<PlanensHensiktType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AdministrativEnhetskodeListe", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdministrativEnhetskodeListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AdministrativEnhetskodeType> _administrativenhetskode;
        
        [System.Xml.Serialization.XmlElementAttribute("administrativenhetskode")]
        public System.Collections.ObjectModel.Collection<AdministrativEnhetskodeType> Administrativenhetskode
        {
            get
            {
                return this._administrativenhetskode;
            }
            private set
            {
                this._administrativenhetskode = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdministrativenhetskodeSpecified
        {
            get
            {
                return (this.Administrativenhetskode.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public AdministrativEnhetskodeListe()
        {
            this._administrativenhetskode = new System.Collections.ObjectModel.Collection<AdministrativEnhetskodeType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FormatertTekstListe", Namespace="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Reguleringsplanforslag/5.0/Pl" +
        "anbestemmelser")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormatertTekstListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<FormatertTekstType> _formaterttekst;
        
        [System.Xml.Serialization.XmlElementAttribute("formaterttekst")]
        public System.Collections.ObjectModel.Collection<FormatertTekstType> Formaterttekst
        {
            get
            {
                return this._formaterttekst;
            }
            private set
            {
                this._formaterttekst = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FormaterttekstSpecified
        {
            get
            {
                return (this.Formaterttekst.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public FormatertTekstListe()
        {
            this._formaterttekst = new System.Collections.ObjectModel.Collection<FormatertTekstType>();
        }
    }
}
